### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, TypedArray, or DataView. Received type undefined

### ISSUE THREAD

**Issue by nsatosh** [nak2k/node-hashed-port#1]
#### version
0.1.0

#### Example code
``` js
const { getPort } = require('hashed-port');

getPort((err, data) => {
  if (err) {
    console.log(err);
  }
  console.log(data);  
});
```

#### Result
```
internal/crypto/hash.js:60
    throw new ERR_INVALID_ARG_TYPE('data',
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, TypedArray, or DataView. Received type undefined
    at Hash.update (internal/crypto/hash.js:60:11)
    at findPort (/path/to/node_modules/hashed-port/lib/index.js:55:11)
    at readJsonFile (/path/to/node_modules/hashed-port/lib/index.js:39:18)
    at ReadFileContext.readFile [as callback] (/path/to/node_modules/hashed-port/lib/index.js:78:16)
```

**Comment by nak2k** [comment]
I've released version 0.1.1 with improved error messages.
